### ISSUE TITLE
Should permissions be fresh install task only?

### ISSUE THREAD

**Issue by dsavell** [dsavell/docker-grav#26]
The permissions section in init-core / init-admin should be fresh only depends on the scenario?

1. building pages outside the container
2. building pages inside container / GRAV CMS

**Comment by Miroka96** [comment]
Hi dsavell,

until now I have always used Grav's admin panel for creating pages. (That's why I also didn't think about Linux specialities with spaces in folder names ;) ). However, as I wouldn't want to limit myself to always use the admin panel, I would prefer to have the permissions fixed every time the container starts (or at least the container is created). Just to prevent strange errors...

Anyway, with the latest fix I am already quite happy :) Thank you!

Best regards,
Miroka
