### ISSUE TITLE
Unable to run any grav command

### ISSUE THREAD

**Issue by aptonline** [dsavell/docker-grav#9]
Issuing any Grav command in the CLI gives me the following error:

`bash: bin/grav: No such file or directory`

I read somewhere (can't find link now) that it may be due to php not having the correct path????

**Comment by dsavell** [comment]
Hey,

Your right, no path is actually set for the Grav BIN, thanks for the contribution.

Will update when fix is out.

**Comment by dsavell** [comment]
@aptonline turns out paths cannot be set due to having to run that binary in the GRAV root directory.

I have fixed working directory this is now set to /var/ww/grav, now commands like bin/grav & bin/gpm can be used directly.

Fixed in the following tags:
latest, core, 1.6.17, core-1.6.17
admin, admin-1.6.17
